services:
  web-app:
    container_name: FastAPI
    build: .
    ports:
      - "8000:8000"
    command: [ "sh", "/app/Scripts/app.sh" ]

  redis:
    container_name: redis
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
